[package]
name = "android-sdk-ui"
version = "0.1.0"
authors = ["triamero <4444613+triamero@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.5.0"
im = "15.0.0"